import turtle


#purple square with no overlap
donatello = turtle.Turtle()
donatello.hideturtle()
donatello.fillcolor("purple")
donatello.begin_fill()
donatello.forward(50)
donatello.left(90)
donatello.forward(50)
donatello.left(90)
donatello.forward(50)
donatello.left(90)
donatello.forward(50)
donatello.left(90)
donatello.end_fill()

#orange regular hexagon with no overlap to square
michelangelo = turtle.Turtle()
michelangelo.hideturtle()
michelangelo.up()
michelangelo.right(90)
michelangelo.forward(20)
michelangelo.down()
michelangelo.fillcolor("orange")
michelangelo.begin_fill()
michelangelo.left(90)
michelangelo.forward(25)
michelangelo.right(60)
michelangelo.forward(25)
michelangelo.right(60)
michelangelo.forward(25)
michelangelo.right(60)
michelangelo.forward(25)
michelangelo.right(60)
michelangelo.forward(25)
michelangelo.right(60)
michelangelo.forward(25)
michelangelo.right(60)
michelangelo.end_fill()

#red non-regular hexagon with no overlap
raphael = turtle.Turtle()
raphael.hideturtle()
raphael.up()
raphael.forward(100)
raphael.down()
raphael.fillcolor("red")
raphael.begin_fill()
raphael.forward(50)
raphael.right(60)
raphael.forward(25)
raphael.right(60)
raphael.forward(25)
raphael.right(60)
raphael.forward(50)
raphael.right(60)
raphael.forward(25)
raphael.right(60)
raphael.forward(25)
raphael.end_fill()

#blue reactangle with no overlap
leonardo = turtle.Turtle()
leonardo.hideturtle()
leonardo.up()
leonardo.left(45)
leonardo.forward(150)
leonardo.down()
leonardo.fillcolor("blue")
leonardo.begin_fill()
leonardo.forward(30)
leonardo.left(90)
leonardo.forward(60)
leonardo.left(90)
leonardo.forward(30)
leonardo.left(90)
leonardo.forward(60)
leonardo.end_fill()
leonardo.showturtle()
